nginx:
    build: ./nginx
    links:
        - node-api1:node-api1
        - node-api2:node-api2
        - node-api3:node-api3
    ports:
        - "80:80"
node-api1:
    build: ./node-api
    links:
        - redis
    ports:
        - "8081:8081"
node-api2:
    build: ./node-api
    links:
        - redis
    ports:
        - "8080"
node-api3:
    build: ./node-api
    links:
        - redis
    ports:
        - "8080"
node-worker:
    build: ./node-worker
    links:
        - redis
redis:
    image: redis
    ports:
        - "6379"
